# Generated by Django 2.0.13 on 2019-03-10 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('level', models.IntegerField()),
                ('task', models.TextField()),
                ('solution', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=200)),
                ('required', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='story.Quest')),
            ],
        ),
        migrations.CreateModel(
            name='Solved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_date', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.Player')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='story.Quest')),
            ],
        ),
    ]
