# Generated by Django 2.0.13 on 2019-03-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20190310_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attitude',
            field=models.CharField(choices=[('hell', 'hell'), ('dunkel', 'dunkel'), ('neutral', 'neutral')], default='neutral', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.CharField(default='uninteressant', max_length=1000),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='title',
            field=models.CharField(choices=[('Chef', 'Chef'), ('Mitläufer', 'Mitläufer'), ('Novize', 'Novize')], default='Novize', max_length=100),
        ),
        migrations.AddField(
            model_name='quest',
            name='is_parallel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quest',
            name='points',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='quest',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
