# Generated by Django 2.0.13 on 2019-03-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_player_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
